class Labels():
    def __init__(self):
        self.dataset_keyword = {
            "ccd_r1__ccdtemps": ["preamp", "ccd0", "ccd1"],
            "vistherm__lamtemps1": ["val1_0", "val1_1", "val1_2", "val1_3", "val1_4", "val1_5", "val1_6", "val1_7"],
            "vistherm__lamtemps2": ["val1_0", "val1_1", "val1_2", "val1_3", "val1_4", "val1_5", "val1_6", "val1_7",
                                    "val1_8"],
            "xcu_r1__coolertemps": ["setpoint", "reject", "tip", "power"],
            "xcu_r1__gatevalve": ["val1", "position"],
            "xcu_r1__heaters": ["h1enabled", "h2enabled", "h1fraction", "h2fraction"],
            "xcu_r1__pressure": ["val1"],
            "xcu_r1__roughpressure1": ["val1"],
            "xcu_r1__temps": ["val1_0", "val1_1", "val1_2", "val1_3", "val1_4", "val1_10", "val1_11"],
            "xcu_r1__turbospeed": ["val1"],
            "xcu_r1__turbotemps": ["bodytemp", "controllertemp"],
            "xcu_r1__turbovaw": ["voltage", "current", "power"]}

        self.dataset_label = \
            {"ccd_r1__ccdtemps_preamp": "Preamp",
             "ccd_r1__ccdtemps_ccd0": "CCD 0",
             "ccd_r1__ccdtemps_ccd1": "CCD 1",
             "vistherm__lamtemps1_val1_0": "Preamp Board",
             "vistherm__lamtemps1_val1_1": "Detect Spider C IN",
             "vistherm__lamtemps1_val1_2": "Cold Strap C OUT",
             "vistherm__lamtemps1_val1_3": "Cold Strap C IN",
             "vistherm__lamtemps1_val1_4": "Thermal Bar C",
             "vistherm__lamtemps1_val1_5": "Detector Box",
             "vistherm__lamtemps1_val1_6": "Detector Plate",
             "vistherm__lamtemps1_val1_7": "Detector Spider C OUT",
             "vistherm__lamtemps2_val1_0": "Red Shield C",
             "vistherm__lamtemps2_val1_1": "Tip",
             "vistherm__lamtemps2_val1_2": "Detect Actuator",
             "vistherm__lamtemps2_val1_3": "Red Tube",
             "vistherm__lamtemps2_val1_4": "Corrector Cell",
             "vistherm__lamtemps2_val1_5": "Cover Detector",
             "vistherm__lamtemps2_val1_6": "Thermal Spreader",
             "vistherm__lamtemps2_val1_7": "Cover Rod C UP",
             "vistherm__lamtemps2_val1_8": "Cover Rod C DOWN",
             "xcu_r1__coolertemps_setpoint": "Cooler Setpoint",
             "xcu_r1__coolertemps_reject": "Cooler Reject",
             "xcu_r1__coolertemps_tip": "Cooler Collar",
             "xcu_r1__coolertemps_power": "Cooler Power",
             "xcu_r1__gatevalve_val1": "val1",
             "xcu_r1__gatevalve_position": "Gatevalve position",
             "xcu_r1__heaters_h1enabled": "Heaters1 ON",
             "xcu_r1__heaters_h2enabled": "Heaters2 ON",
             "xcu_r1__heaters_h1fraction": "Heaters1 POWER",
             "xcu_r1__heaters_h2fraction": "Heaters2 POWER",
             "xcu_r1__pressure_val1": "Gauge Pressure",
             "xcu_r1__roughpressure1_val1": "Roughing Station Pressure",
             "xcu_r1__temps_val1_0": "Temp Detector box",
             "xcu_r1__temps_val1_1": "Temp Mangin",
             "xcu_r1__temps_val1_2": "Temp Spider",
             "xcu_r1__temps_val1_3": "Thermal Spreader",
             "xcu_r1__temps_val1_4": "TempIDG_Front Ring",
             "xcu_r1__temps_val1_10": "TempIDG_Detector Thermal assy1",
             "xcu_r1__temps_val1_11": "TempIDG_Detector Thermal assy2",
             "xcu_r1__turbospeed_val1": "Turbo Speed",
             "xcu_r1__turbotemps_bodytemp": "Turbo Body Temperature",
             "xcu_r1__turbotemps_controllertemp": "Turbo Controller Temperature",
             "xcu_r1__turbovaw_voltage": "Turbo Voltage",
             "xcu_r1__turbovaw_current": "Turbo Current",
             "xcu_r1__turbovaw_power": "Turbo Power"}
